### ISSUE TITLE
[1.10.2] World Crash using Electrical Advantage Pump With EIO Pressurised Fluid Conduit

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/ElectricAdvantage#1]
![mmd crash](https://cloud.githubusercontent.com/assets/10524952/18529134/37e7e042-7b0f-11e6-8fb0-463f2783681f.png)
The Above pic shows the exact setup i was using to make the crash happen. Essentially setting it up to transfer lava using the Electrical Adantage Pump to send the lava through fluid conduit into Dimensional trasciever hooked up to a Mk2 lava Generator in the overworld which is connected to a Dimensional trsciever set to recieve the lava. I tested this same setup transfering water and it only crashed using Pressurised Fluid Conduits, normal Fluid Conduits work fine.
Crash Report @ http://pastebin.com/ueWBUBJy

https://github.com/SleepyTrousers/EnderIO/issues/3694

**Comment by dshadowwolf** [comment]
Looks like, when the tank of the pump is empty, it still tries to reference the fluid in the tank.

After referencing the most recent Forge documentation I could find about IFluidHandler and FluidTank, the solution was as simple as doing a simulated drain of the pumps internal tank - a simulated drain of 0mB :)

#5 works as a fix in my test setup - Though I did not test a Nether->Overworld link, I was able to reproduce just by putting a pipe on the pump and trying to empty it, causing the game to crash. That does not happen with the change in this PR.
